config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  
  devise_for :users, controllers:{omniauth_callbacks: "users/omniauth_callbacks"}
  
  post "/", to: "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/notfound", to: "static_pages#notfound"
  get "/tour", to:"tour_bookings#tour"
  get "/booking", to: "tour_bookings#new_booking"
  post "/booking", to: "tour_bookings#create_booking"
  get "/userbooking", to: "users#booking"
  get "/paymenthistory", to: "users#payment_history"
  get "/admin", to: "static_pages#admin_home"
  post "/recharge", to: "users#recharge"

  
  resources :users, only: [:show, :index]
  resources :posts
  resources :comments, only: [:create, :destroy]
  resources :tour_bookings
  resources :payments
  resources :account_activations, only: :edit
  resources :password_resets, except: [:index, :show, :destroy]

  namespace :admin do
    resources :categories, :slides, :tours, :bookings, :coupons
    resources :tours do
      resources :tourdetails
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout :user_layout 

  def home
    if params[:commit].nil?
      @posts = Post.order_by_newest.paginate(page: params[:page], per_page: Settings.per_page)
      @tours = Tour.tour_most_booking.paginate(page: params[:page], per_page: Settings.per_page)
      @tours = Tour.tour_by_category(params[:id_category_tour]).
        paginate(page: params[:page], per_page: Settings.per_page) if params[:id_category_tour]
      @posts = Post.post_by_category(params[:id_category_post]).
        paginate(page: params[:page], per_page: Settings.per_page) if params[:id_category_post]
    else
      title_cont = params[:name]
      @posts = Post.ransack({title_cont: title_cont}).result
      @tours = Tour.ransack({price_discount_gteq: params[:price_from],
        price_discount_lteq: params[:price_to], title_cont: title_cont}).result
    end
  end

  def admin_home
    authorize! :read, :admin_home
    revenue_per_month = Booking.select_revenue_all_month
    @data = {
      labels: revenue_per_month.keys,
      datasets: [
        {
          label: t(".statistical"),
          backgroundColor: "rgba(220,220,220,0.2)",
          borderColor: "rgba(220,220,220,1)",
          data: revenue_per_month.values
        }
      ]
    }
    @options = {}
  end

  def contact; end

  def about; end

  def notfound; end

  private 
  def user_layout
    return "admin" if current_user&.admin?
    "application"
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
  def check_active(slide)
    return true if slide.active
    false
  end

  def show_image_slide(slide)
    image_tag(slide.image.url, alt: slide.name, height: Settings.heigth_slide, width: Settings.width_slide)
  end

  def category_post
    Category.user
  end

  def category_tour
    Category.admin
  end

  def slide_all
    Slide.all
  end
end

app/views/static_pages/_slider.html.erb
<div  id="myCarousel" class="carousel slide margintopbottom" data-ride="carousel">
  <div class="carousel-inner">
    <% slide_all.each do |slide| %>
      <% if check_active(slide) %>
        <div class="item active">
          <%= show_image_slide(slide) %>
        </div>
      <% else %>
        <div class="item">
          <%= show_image_slide(slide) %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= link_to "#myCarousel", class: "left carousel-control", "data-slide" => "prev" do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only"><%= t(".previous") %></span>
  <% end %>
  <%= link_to "#myCarousel", class: "right carousel-control", "data-slide" => "next" do %>
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only"><%= t(".next") %></span>
  <% end %>
</div>

app/views/static_pages/about.html.erb
<%= provide(:title, t(".title_about")) %>
<%= t(".about_us") %>

app/views/static_pages/admin_home.html.erb
<div>
  <h3 class="text-center"><%= t(".booking_manager") %></h3>
</div>
<div class="row">
  <div class="col-sm-2">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= t(".manager_category") %></h5>
        <%= link_to t(".manager_category"), admin_categories_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  <div class="col-sm-2">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= t(".manager_slide") %></h5>
        <%= link_to t(".manager_slide"), admin_slides_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  <div class="col-sm-2">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= t(".manager_tour") %></h5>
        <%= link_to t(".manager_tour"), admin_tours_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>

  <div class="col-sm-2">
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= t(".manager_coupon") %></h5>
          <%= link_to t(".manager_coupon"), admin_coupons_path, class: "btn btn-primary" %>
        </div>
      </div>
  </div>

  <div class="col-sm-2">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= t(".manager_user") %></h5>
        <%= link_to t(".manager_user"), users_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>

  <div class="col-sm-2">
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= t(".manager_booking") %></h5>
          <%= link_to t(".manager_booking"), admin_bookings_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
</div>
<div class="row">
  <%= line_chart @data, @options %>
</div>

app/views/static_pages/contact.html.erb
<%= provide(:title, t(".title_contact")) %>
<%= t(".contact_us") %>

app/views/static_pages/home.html.erb
<%= provide(:title, t(".title_home")) %>
<%= render "slider" %>
<div class="row">
  <div class="col-sm-3">
    <ul class="list-group">
      <h3 class="text-center"><%= t(".category_tour") %></h3>
      <% category_tour.each do |category| %>
        <%= link_to category.name, root_path(id_category_tour: category.id), class: "list-group-item" %>
      <% end %>
    </ul>
    <div id="search">
      <%= render "shared/search" %>
    </div>
    <ul class="list-group">
      <h3 class="text-center"><%= t(".category_post") %></h3>
      <% category_post.each do |category| %>
        <%= link_to category.name, root_path(id_category_post: category.id), class: "list-group-item" %>
      <% end %>
    </ul>
  </div>
  <div class="col-sm-9">
    <div class="row">
      <h3 class="text-center"><%= t(".tour_newest") %></h3>
      <%= render "shared/tours" %>
    </div>
    <div class="row">
        <h3 class="text-center"><%= t(".post_newest") %></h3>
        <%= render "shared/posts" %>
      </div>
  </div>
</div>

app/views/static_pages/notfound.html.erb
<%= provide(:title, t("title_notfound")) %>
<p><%= flash[:danger] if flash[:danger] %></p>