config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  
  devise_for :users, controllers:{omniauth_callbacks: "users/omniauth_callbacks"}
  
  post "/", to: "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/notfound", to: "static_pages#notfound"
  get "/tour", to:"tour_bookings#tour"
  get "/booking", to: "tour_bookings#new_booking"
  post "/booking", to: "tour_bookings#create_booking"
  get "/userbooking", to: "users#booking"
  get "/paymenthistory", to: "users#payment_history"
  get "/admin", to: "static_pages#admin_home"
  post "/recharge", to: "users#recharge"

  
  resources :users, only: [:show, :index]
  resources :posts
  resources :comments, only: [:create, :destroy]
  resources :tour_bookings
  resources :payments
  resources :account_activations, only: :edit
  resources :password_resets, except: [:index, :show, :destroy]

  namespace :admin do
    resources :categories, :slides, :tours, :bookings, :coupons
    resources :tours do
      resources :tourdetails
    end
  end
end

app/models/slide.rb
class Slide < ApplicationRecord
  validates :name, presence: true,
    length: { maximum: Settings.length_max_slidename }
  mount_uploader :image, ImageUploader
end

app/controllers/admin/slides_controller.rb
class Admin::SlidesController < ApplicationController
  authorize_resource
  
  before_action :load_slide, except: [:index, :create, :new]

  def index
    @slides = Slide.paginate(page: params[:page], per_page:  Settings.def_perpage)
  end

  def create 
    @slide = Slide.new slide_params
    params[:slide][:active] = Settings.checkbox_true ? true: false
    if @slide.save
      load_slides
    end
    respond_to do |format|
      format.js
    end
  end

  def new
    @slide = Slide.new
    respond_to do |format|
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    if @check_update = @slide.update_attributes(slide_params)
      flash[:success] = t ".slide_update_success"
    end
    respond_to do |format|
      format.js
    end
  end

  def destroy
    if @slide.destroy
      flash[:success] = t ".delete_success"
      redirect_to admin_slides_path
    end
  end

  private
  def slide_params
    params.require(:slide).permit(:name, :image, :active)
  end

  def load_slide
    @slide = Slide.find_by(id: params[:id])
    unless @slide
      flash.now[:danger] = t ".slide_notfound"
      redirect_to notfound_path
    end
  end

  def load_slides
    @slides = Slide.paginate(page: Settings.def_page, per_page: Settings.def_perpage)
  end
end

app/helpers/admin/slides_helper.rb
module Admin::SlidesHelper
end

app/views/admin/slides/_edit.html.erb
<%= provide(:url_action, admin_slide_path) %> 
<%= provide(:button_title, t(".update")) %>

<h1 class="text-center"><%= t(".edit_slide") %></h1> 
<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <%= render "form" %>
  </div>
</div>

app/views/admin/slides/_form.html.erb
<%= form_for @slide, html: {multipart: true }, url: yield(:url_action), remote: true do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label t(".name") %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label t("active") %>
  <%= f.check_box :active %>

  <div class="form-group">
    <%= f.file_field t(".image"), accept: t(".accetp_file") %>
  </div>
  <%= f.submit yield(:button_title), class: "btn btn-primary" %>
<% end %>

app/views/admin/slides/_new.html.erb
<%= provide(:url_action, admin_slides_path) %>
<%= provide(:button_title, t(".create")) %>

<h1 class="text-center"><%= t(".create_slide") %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <%= render "form" %>
  </div>
</div>

app/views/admin/slides/_slide.html.erb
<tr>
  <td><%= show_image(slide) %></td>
  <td><%= slide.name %></td>
  <td class="row">
    <%= link_to t(".delete"), admin_slide_path(slide), method: :delete, 
      data: { confirm: t(".cofirm_delete") }, class: "btn btn-primary" %>
    <%= link_to t(".edit"), edit_admin_slide_path(slide),
      { class: "btn btn-primary", "data-toggle" => "modal",
        "data-target" => "#myModal", remote: true } %>
  </td>
</tr>

app/views/admin/slides/create.js.erb
var isSuccess = '<%= @slide.valid? %>'
if (isSuccess == 'true') {
  alert('Create Success!')
  $('#slide_body').html('<%= j render @slides %>')
  $('#paginate_slide').html('<%= j will_paginate %>')
} 
else $('#myModal #body_modal').html('<%= j render "new" %>')

app/views/admin/slides/edit.html.erb
<%= provide(:title, t(".edit_slide")) %>

<h1 class="text-center"><%= t(".edit_slide") %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
     <%= render "form" %>
  </div>
</div>

app/views/admin/slides/index.html.erb
<% provide :title, t(".slide_title") %>
<h1><%= t(".slide_title") %></h1>
<%= link_to t(".create"), new_admin_slide_path, { class: "btn btn-primary",
  "data-toggle" => "modal", "data-target" => "#myModal", remote: true } %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t(".image") %></th>
      <th><%= t(".name") %></th>
      <th><%= t(".action") %></th>
    </tr>
  </thead>
  <tbody id="slide_body">
    <%= render @slides %>
  </tbody>
</table>
<div id="paginate_slide">
  <%= will_paginate %>
</div>
  
<%= render "shared/modal" %>