config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  
  devise_for :users, controllers:{omniauth_callbacks: "users/omniauth_callbacks"}
  
  post "/", to: "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/notfound", to: "static_pages#notfound"
  get "/tour", to:"tour_bookings#tour"
  get "/booking", to: "tour_bookings#new_booking"
  post "/booking", to: "tour_bookings#create_booking"
  get "/userbooking", to: "users#booking"
  get "/paymenthistory", to: "users#payment_history"
  get "/admin", to: "static_pages#admin_home"
  post "/recharge", to: "users#recharge"

  
  resources :users, only: [:show, :index]
  resources :posts
  resources :comments, only: [:create, :destroy]
  resources :tour_bookings
  resources :payments
  resources :account_activations, only: :edit
  resources :password_resets, except: [:index, :show, :destroy]

  namespace :admin do
    resources :categories, :slides, :tours, :bookings, :coupons
    resources :tours do
      resources :tourdetails
    end
  end
end

app/models/tour.rb
# frozen_string_literal: true

class Tour < ApplicationRecord
  acts_as_paranoid
  
  belongs_to :category
  has_many :ratings, dependent: :destroy
  has_many :tourdetails, dependent: :destroy
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images
  scope :order_by_newest, -> { order(created_at: :desc) }
  scope :tour_by_category, -> (id_category) { where(category_id: id_category )}
  before_save :calculator_price_discount
  before_update :calculator_price_discount
  validates :category_id, presence: :true

  ransack_alias :tour, :title_or_content
  
  def calculator_price_discount
    self.price_discount = self.price - self.price * (self.discount / 100 )
  end

  class << self
    def tour_most_booking
      joins(:tourdetails).select("tours.*, sum(tourdetails.total_current_booking) as total_booking").
        group("tourdetails.tour_id").order("total_booking DESC")
    end
  end

  def is_booking_tour
    tourdetails.each do |tourdetail|
      return true if tourdetail.total_current_booking > 0
    end
  end
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < ApplicationController
  authorize_resource
  
  before_action :load_tour, only: [:edit, :update, :destroy,:show]
  before_action :check_booking_tour, only: :destroy

  def index
    @q = Tour.ransack(params[:q]) 
    if params[:q].nil?
      @tours = Tour.order_by_newest.paginate page: params[:page], per_page: Settings.def_perpage
    else
      @tours = @q.result(distinct: true).paginate page: params[:page], per_page: Settings.def_perpage
    end
  end

  def listtour
    @tour_details = @tour.tourdetails
  end

  def new
    @tour = Tour.new
    @image = @tour.images.build
  end
  
  def create
    @tour = Tour.new params_tour
    if @tour.save
      params[:images][:image_link].each do |image|
        @image_attachment = @tour.images.create!(image_link: image, tour_id: @tour.id)
      end
      redirect_to admin_tours_path
    else
      flash[:danger] = t ".create_tour_failed"
      render :new
    end
  end
  
  def update
    if @tour.update_attributes(params_tour)
      flash[:success] = t ".update_success"
      redirect_to admin_tours_path
    else
      flash[:danger] = t ".update_tour_failed"
      render :edit
    end
  end

  def edit; end

  def destroy
    check_booking_tour
    if @tour.destroy
      flash[:success] = t ".delete_success"
      redirect_to admin_tours_path
    else
      flash[:success] = t ".delete_failed"
      redirect_to notfound_path
    end
  end

  private
  def check_booking_tour
    unless @tour.is_booking_tour
      flash[:danger] = t ".tour_having_booking"
      redirect_to admin_tours_path
    end
  end

  def params_tour
    params.require(:tour).permit(:title, :address_source, :price, :discount, :price_discount,
      :total_day, :start_days, :content, :category_id, :total_member_max, :images, :description)
  end

  def load_tour
    @tour = Tour.find_by(id: params[:id])
    unless @tour
      redirect_to notfound_path
    end
  end
end

app/helpers/admin/tours_helper.rb
# frozen_string_literal: true

module Admin::ToursHelper
  def load_categories
    Category.admin.collect{ |u| [u.name, u.id] }
  end

  def load_categories_user
    Category.user.collect{ |u| [u.name, u.id] }
  end

  def check_address_present(tour)
    unless tour.address_source.nil?
      tour.address_source.split("\r\n")
    else
      ""
    end
  end
end

app/views/admin/tours/_form.html.erb
<%= form_for @tour, html: {multipart: true }, url: yield(:url_action) do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label t(".title") %>
  <%= f.text_field :title, class: "form-control", required: true %>

  <%= f.label t(".description") %>
  <%= f.text_area :description, class: "form-control", required: true %>

  <%= f.label t(".address_source") %>
  <%= f.select :address_source, options_for_select(load_address, check_address_present(@tour)), {}, { :class => "form-control chosen-select", :required => true } %>
  
  <%= f.label t(".price") %>
  <%= f.number_field :price, class: "form-control", required: true %>

  <%= f.label t(".discount") %>
  <%= f.number_field :discount, step: Settings.step_price, class: "form-control", required: true %>

  <%= f.label t(".total_day") %>
  <%= f.text_field :total_day, class: "form-control", required: true %>

  <%= f.label t(".total_member_max") %>
  <%= f.text_field :total_member_max, class: "form-control", required: true %>
  
  <%= f.fields_for :images do |p| %>
     <div class="field">
       <%= p.label t(".image") %><br>
       <%= p.file_field :image_link, :multiple => true, name: "images[image_link][]" %>
     </div>
   <% end %>  

  <%= f.label t(".content") %>
  <%= f.text_area :content, rows: Settings.row_default, cols: Settings.col_default, class: "wysihtml5" %> 

  <%= f.label t(".category") %>
  <%= f.select :category_id, options_for_select(load_categories, @tour.category_id), {}, { class: "form-control", required: true } %>

  <%= f.submit yield(:button_title), class: "form-control btn btn-primary" %>
<% end %>
<script type="text/javascript">
  
</script>

app/views/admin/tours/_tour.html.erb
<tr>
  <td><%= tour.title %></td>
  <td><%= tour.category.name %></td>
  <td><%= tour.address_source %></td>
  <td><%= tour.price %></td>
  <td><%= tour.price_discount %></td>
  <td><%= tour.total_day %></td>
  <td><%= tour.total_member_max %></td>
  <td><%= tour.total_member_current %></td>
  <td><%= tour.rating_average %></td>
  <td class="row">
    <%= link_to t(".edit"), edit_admin_tour_path(tour), class: "col-sm-6 btn btn-primary" %>
    <%= link_to t(".delete"), admin_tour_path(tour), method: :delete, 
          data: { confirm: t(".cofirm_delete") }, class: "col-sm-6 btn btn-danger" %>
    <%= link_to t(".tour_detail"), admin_tour_tourdetails_path(tour),
          class: "col-sm-6 btn btn-warning" %>
  </td> 
</tr>

app/views/admin/tours/edit.html.erb
<%= provide(:url_action, admin_tour_path) %>
<%= provide(:button_title, t(".edit")) %>

<h1 class="text-center"><%= t(".edit_tour") %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <%= render "form" %>
  </div>
</div>

app/views/admin/tours/index.html.erb
<% provide :title, t(".tour_title") %>
<h1><%= t(".tour_title") %></h1>
<%= link_to t(".create"), new_admin_tour_path, {class: "btn btn-primary"} %>
<br>

<div class="form-search">
  <%= search_form_for(@q, url: admin_tours_path) do |f| %>
    <%= f.search_field :tour_cont, class: "form-control" %>
    <%= f.submit t(".search"), class: "btn btn-search" %>
  <% end %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sort_link(@q, :title, t(".title"), default_order: :asc) %></th>
      <th><%= t(".category_name") %></th>
      <th><%= t(".address_source") %></th>
      <th><%= t(".price") %></th>
      <th><%= t(".price_discount") %></th>
      <th><%= t(".total_day") %></th>
      <th><%= t(".total_member_max") %></th>
      <th><%= t(".total_member_current") %></th>
      <th><%= t(".rating_average") %></th>
      <th><%= t(".action") %></th>
    </tr>
  </thead>
  <tbody id="tour_body">
    <% if @tours.empty? %>
      <tr>
        <td>
          <%= t(".empty") %>
        </td>
      </tr>
    <% else %>
      <%= render @tours %>
    <% end  %>
  </tbody>
</table>
<div id="paginate_tour">
  <%= will_paginate %>
</div>

app/views/admin/tours/new.html.erb
<%= provide(:url_action, admin_tours_path) %>
<%= provide(:button_title, t(".create")) %>

<h1 class="text-center"><%= t(".create_tour") %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <%= render "form" %>
  </div>
</div>

app/views/admin/tours/show.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= render "shared/slider_tour" %>
  </div>
  <div class="col-sm-6 center_mid">
    <div class="row text-center">
      <h2 class="color-red"><%= @tour.title %></h2>
    </div>
    <div class="row">
      <div class="col-sm-3">
        <%= t(".start_day") %>
      </div>
      <div class="col-sm-3">
        <%= link_to t(".select_day"), tour_path(id: 1), class: "btn btn-primary" %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3">
        <%= t(".total_day") %>
      </div>
      <div class="col-sm-3">
        <%= @tour.total_day %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3">
        <%= t(".source_address") %>
      </div>
      <div class="col-sm-3">
        <%= @tour.address_source %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3">
        <%= t(".price") %>
      </div>
      <div class="col-sm-3">
        <%= @tour.price %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3">
        <%= t(".price_discount") %>
        <%= t(".total_booking") %>
      </div>
      <div class="col-sm-3">
        <%= @tour.price_discount %>
        <p><span><%= @tour.total_member_current %></span>/<span class="color-red"><%= @tour.total_member_max %></span></p>
      </div>
      <div class="col-sm-3">
        <%= link_to t(".booking"), book_path(tour_id: @tour.id), class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

<div class="row container-fluid">
  <h3 class="text-center"><%= t(".tour_guide") %></h3>
  <%= @tour.content.html_safe %>
</div>