config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  
  devise_for :users, controllers:{omniauth_callbacks: "users/omniauth_callbacks"}
  
  post "/", to: "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/notfound", to: "static_pages#notfound"
  get "/tour", to:"tour_bookings#tour"
  get "/booking", to: "tour_bookings#new_booking"
  post "/booking", to: "tour_bookings#create_booking"
  get "/userbooking", to: "users#booking"
  get "/paymenthistory", to: "users#payment_history"
  get "/admin", to: "static_pages#admin_home"
  post "/recharge", to: "users#recharge"

  
  resources :users, only: [:show, :index]
  resources :posts
  resources :comments, only: [:create, :destroy]
  resources :tour_bookings
  resources :payments
  resources :account_activations, only: :edit
  resources :password_resets, except: [:index, :show, :destroy]

  namespace :admin do
    resources :categories, :slides, :tours, :bookings, :coupons
    resources :tours do
      resources :tourdetails
    end
  end
end

app/models/tourdetail.rb
# frozen_string_literal: true

class Tourdetail < ApplicationRecord
  acts_as_paranoid

  belongs_to :tour
  has_one :booking, dependent: :destroy
  scope :order_early_current, -> { order(day_start: :asc)}
  scope :day_early_current, -> { where("day_start >= ?", Time.now) }
  validates :total_booking, presence: true, length: {minimum: Settings.minimun}
  validates :total_current_booking, presence: true, length: {minimum: Settings.minimun}
  validates :day_start, presence: true
  validate do
    day_start_large_than_day_current
  end

  def check_booking
    return true if total_current_booking < total_booking
    false
  end

  class << self
    def tour_most_booking
      select("tours.*, sum(tourdetail.id) as sum_booking").joins(:tours)
        .group("tours.id").order("sum_booking DESC")
    end
  end

  private 
  def day_start_large_than_day_current
    return if day_start.nil? || day_start >= Time.now
    errors.add(:day_start, "day start valid")
  end
end

app/controllers/admin/tourdetails_controller.rb
class Admin::TourdetailsController < ApplicationController
  authorize_resource
  
  before_action :load_tour, only: [:edit, :index, :new, :destroy, :create]
  before_action :load_tour_detail, only: [:edit, :update, :destroy]

  def index
    @tourdetails = @tour.tourdetails.paginate(page: params[:page], per_page: Settings.def_perpage)
  end
 
  def new
    @tourdetail = @tour.tourdetails.build
  end

  def create
    @tourdetail = Tourdetail.new params_tour_detail
    if @tourdetail.save
      load_tour
      flash[:success] = t ".create_success"
      redirect_to admin_tour_tourdetails_path(@tour)
    else
      render :new
    end
  end

  def edit
  end
  
  def update
    if @tourdetail.update_attributes(params_tour_detail)
      flash[:success] = t ".update_success"
      load_tour
      redirect_to admin_tour_tourdetails_path(@tour)
    else
      render :edit
    end
  end

  def destroy
    if @tourdetail.total_current_booking > 0
      flash[:danger] = t ".danger_booking"
      if @tourdetail.destroy
        flash[:success] = t ".delete_success"
      else
        flash[:danger] = t ".delete_failed"
      end
    else
      begin
        ActiveRecord::Base.transaction do
        if @tourdetail.really_destroy!
          flash[:success] = t ".delete_success"
        else
          flash[:danger] = t ".delete_failed"
        end
        rescue ActiveRecord::RecordInvalid => exception
          flash[:danger] = t ".error_system"
        end
      end
    end
    redirect_to admin_tour_tourdetails_path(@tour)
  end
  
  private 
  def params_tour_detail
    params.require(:tourdetail).permit(:day_start, :tour_id, :total_booking)
  end
  
  def load_tour
    @tour = Tour.find_by(id: params[:tour_id])
    unless @tour
      flash[:danger] = t ".tour_notfound"
      redirect_to notfound_path
    end
  end

  def load_tour_detail
    @tourdetail = Tourdetail.find_by(id: params[:id])
    unless @tourdetail
      flash[:danger] = t ".tourdetail_notfound"
      redirect_to notfound_path
    end
  end
end

app/helpers/admin/tourdetails_helper.rb
module Admin::TourdetailsHelper
end

app/views/admin/tourdetails/_form.html.erb
<%= form_for @tourdetail, url: yield(:url_action) do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.hidden_field :total_booking, value: @tour.total_member_max %>
  <%= f.hidden_field :tour_id, value: @tourdetail.tour_id %>

  <%= f.label t(".day_start") %>
  <%= f.datetime_field :day_start, class: "form-control" %>

  <%= f.submit yield(:button_title), class: "form-control btn btn-primary" %>
<% end %>

app/views/admin/tourdetails/_tourdetail.html.erb
<tr>
  <td><%= tourdetail.day_start %></td>
  <td><%= link_to tourdetail.total_current_booking, admin_booking_path(id: tourdetail.id) %></td>
  <td>
    <%= link_to t(".edit"), edit_admin_tour_tourdetail_path(tourdetail.tour,tourdetail), class: "col-sm-6 btn btn-primary" %>
    <%= link_to t(".delete"), admin_tour_tourdetail_path(tourdetail.tour, tourdetail), method: :delete, 
          data: { confirm: t(".cofirm_delete") }, class: "col-sm-6 btn btn-danger" %>
  </td>
</tr>

app/views/admin/tourdetails/edit.html.erb
<%= provide(:url_action, admin_tour_tourdetail_path(@tour)) %>
<%= provide(:button_title, t(".edit_tour_detail")) %>

<h1 class="text-center"><%= t(".edit_tour_detail") %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <%= render "form" %>
  </div>
</div>

app/views/admin/tourdetails/index.html.erb
<% provide :title, t(".tourdetail_title") %>
<h1><%= t(".tourdetail_title") %></h1>
<%= link_to t(".create"), new_admin_tour_tourdetail_path, class: "btn btn-primary" %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t(".start_day") %></th>
      <th><%= t(".total_current_booking") %></th>
      <th><%= t(".action") %></th>
    </tr>
  </thead>
  <tbody>
    <%= render @tourdetails %>
  </tbody>
</table>
<div>
  <%= will_paginate %>
</div>
  

app/views/admin/tourdetails/new.html.erb
<%= provide(:url_action, admin_tour_tourdetails_path) %>
<%= provide(:button_title, t(".create_tour_detail")) %>

<h1 class="text-center"><%= t(".create_tour_detail") %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <%= render "form" %>
  </div>
</div>

app/views/admin/tourdetails/show.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= render "shared/slider_tour" %>
  </div>
  <div class="col-sm-6 center_mid">
    <div class="row text-center">
      <h2 class="color-red"><%= @tour.title %></h2>
    </div>
    <div class="row">
      <div class="col-sm-3">
        <%= t(".start_day") %>
      </div>
      <div class="col-sm-3">
        <%= @tour_detail.day_start %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3">
        <%= t(".total_day") %>
      </div>
      <div class="col-sm-3">
        <%= @tour.total_day %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3">
        <%= t(".source_address") %>
      </div>
      <div class="col-sm-3">
        <%= @tour.address_source %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3">
        <%= t(".price") %>
      </div>
      <div class="col-sm-3">
        <%= @tour.price %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3">
        <%= t(".price_discount") %>
        <%= t(".total_booking") %>
      </div>
      <div class="col-sm-3">
        <%= @tour.price_discount %>
        <p><span><%= @tour.total_member_current %></span>/<span class="color-red"><%= @tour.total_member_max %></span></p>
      </div>
      <div class="col-sm-3">
        
      </div>
    </div>
  </div>
</div>

<div class="row container-fluid">
  <h3 class="text-center"><%= t(".tour_guide") %></h3>
  <%= @tour.content.html_safe %>
</div>